# Generated by Django 5.1.1 on 2025-07-11 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='project',
            field=models.ForeignKey(limit_choices_to={'status': 'open'}, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='app.project'),
        ),
        migrations.AlterField(
            model_name='link',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
