# Generated by Django 5.1.1 on 2024-10-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_company_options_alter_companycontact_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
