# Generated by Django 5.1.1 on 2025-08-12 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_candidatenote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CandidateNote',
        ),
    ]
