# Generated by Django 5.1.1 on 2025-08-22 13:17

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_candidatenote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text',
            field=django_quill.fields.QuillField(),
        ),
    ]
