# Generated by Django 5.1.1 on 2024-10-17 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_status_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.ForeignKey(blank=True, default='Lead/Applied', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statuses', to='app.status'),
        ),
    ]
