# Generated by Django 5.1.1 on 2024-10-17 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_submission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='candidates', to='app.tag'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='app.status'),
        ),
    ]
