# Generated by Django 5.1.1 on 2025-08-04 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_note_text'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='link',
            unique_together={('candidate', 'project')},
        ),
    ]
