# Generated by Django 5.1.1 on 2024-11-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_candidate_created_at_candidate_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['updated_at']},
        ),
        migrations.AddField(
            model_name='candidate',
            name='current_company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='current_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
