# Generated by Django 5.1.1 on 2024-11-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_candidate_options_candidate_current_company_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Status'},
        ),
        migrations.RemoveField(
            model_name='submission',
            name='notes',
        ),
        migrations.AddField(
            model_name='submission',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
