# Generated by Django 5.1.1 on 2025-10-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_note_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='parsed_resume',
            field=models.TextField(blank=True),
        ),
    ]
