# Generated by Django 5.1.1 on 2024-11-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_status_options_remove_submission_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['order'], 'verbose_name_plural': 'Status'},
        ),
        migrations.AddField(
            model_name='status',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
