# Generated by Django 5.1.1 on 2024-11-21 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_candidate_options_alter_status_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linked_to',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked', to='app.candidate')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked', to='app.project')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked', to='app.status')),
            ],
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
