# Generated by Django 5.1.1 on 2024-11-21 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_project_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='created_date',
            new_name='creation_date',
        ),
    ]
