# Generated by Django 5.1.1 on 2025-03-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_location_user_status_user_tag_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='status',
            field=models.CharField(choices=[('sourced', 'Sourced'), ('lead-applied', 'Lead/Applied'), ('outreach', 'Outreach - Linkedin/Email'), ('phone screen', 'Phone Screen'), ('submitted', 'Submitted'), ('rejected', 'Rejected'), ('onsite', 'Onsite'), ('hired', 'Hired')], default='sourced', max_length=30),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
