# Generated by Django 5.1.1 on 2025-03-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_link_status_delete_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='status',
            field=models.CharField(choices=[('sourced', 'Sourced'), ('lead-applied', 'Lead/Applied'), ('outreach', 'Outreach - Linkedin/Email'), ('phone screen', 'Phone Screen'), ('submitted', 'Submitted'), ('rejected', 'Rejected'), ('interview', 'Interview'), ('onsite', 'Onsite'), ('hired', 'Hired')], default='sourced', max_length=30),
        ),
    ]
