# Generated by Django 5.1.1 on 2025-03-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_link_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='resume',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='resume'),
        ),
    ]
